language: python
python:
  - "2.7"

# - "3.4"

# command to install dependencies
install:
  - pip install -q coveralls
  - pip install -q -r build-requirements.txt -r test-requirements.txt

script: ./.travis-ci.sh

after_script:
  - coveralls
