language: python
python:
  - "2.7"

# - "3.4"

# command to install dependencies
install:
  - pip install -q coveralls
  - pip install -r build-requirements.txt -r test-requirements.txt

script:
  - setup.py build
  - coverage run --source=eventstreamr2 setup.py test flake8

after_script:
  - coveralls
